---
- name: Import certificates into ISE
  gather_facts: false
  hosts: ise-ppan-test
  vars_files:
    - "{{ ansible_config_file | dirname }}/vars/isedtea.yaml"

  tasks:
    - name: Process ISRG Cert Raw Data
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' '/Users/chmoreto/Labs/ISEDTEA/certs/trusted/1-ISRG Root X1.pem'
      register: isrg_cert_raw

    - name: Process E5 Cert Raw Data
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' '/Users/chmoreto/Labs/ISEDTEA/certs/trusted/2-E5.pem'
      register: e5_cert_raw

    - name: Process LetsEncrypt Cert Raw Data
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' '/Users/chmoreto/Labs/ISEDTEA/certs/trusted/3-letsencrypt.org.pem'
      register: lencr_cert_raw

# ----------------------------------------------------------------------------
# Using the `cisco.ise.system_certificate_import` module always failed for me with this very informative error message:
# ok: [ise-span-test] => changed=false 
#   ise_response:
#     response:
#       id: null
#       message: null
#       status: null
#     version: 1.0.1
#   result: ''
#
# Due to this, I have used the API to import the System Certificates
# ----------------------------------------------------------------------------

    - name: Import ISRG Root Trusted certificate on {{ inventory_hostname }} via API
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://ise-ppan-test.isedtea.net/api/v1/certs/trusted-certificate/import
        method: POST
        url_username: iseadmin
        url_password: ISEisC00L
        force_basic_auth: yes
        body: |
          { 
            "allowBasicConstraintCAFalse": true,
            "allowMultipleCNCert": false,
            "allowOutOfDateCert": true,
            "allowSHA1Certificates": true,
            "data": "{{isrg_cert_raw.stdout}}",
            "description": "ISRG Root Certificate",
            "name": "ISRG Root Certificate",
            "trustForCertificateBasedAdminAuth": false,
            "trustForCiscoServicesAuth": true,
            "trustForClientAuth": false,
            "trustForIseAuth": false,
            "validateCertificateExtensions": false
          }
        status_code: [
                      200,  # Created Certificate
                      201,  # Created
                      405,  # Invalid input
                      409,  # Certificate already exists
                      500,  # Internal server error
                      ]
        body_format: json
        validate_certs: "{{ ise_verify }}"
        return_content: true
        timeout: 600 # in seconds (10 minutes)
      register: response
      failed_when: (response.status != 200) and (response.status != 500)
      ignore_errors: true

    # - name: Import E5 Root Trusted certificate on {{ inventory_hostname }} via API
    #   delegate_to: localhost
    #   ansible.builtin.uri:
    #     url: https://ise-ppan-test.isedtea.net/api/v1/certs/trusted-certificate/import
    #     method: POST
    #     url_username: iseadmin
    #     url_password: ISEisC00L
    #     force_basic_auth: yes
    #     body: |
    #       { 
    #         "allowBasicConstraintCAFalse": true,
    #         "allowMultipleCNCert": false,
    #         "allowOutOfDateCert": true,
    #         "allowSHA1Certificates": true,
    #         "data": "{{e5_cert_raw.stdout}}",
    #         "description": "E5 Root CA",
    #         "name": "E5 Root Certificate",
    #         "trustForCertificateBasedAdminAuth": false,
    #         "trustForCiscoServicesAuth": true,
    #         "trustForClientAuth": false,
    #         "trustForIseAuth": false,
    #         "validateCertificateExtensions": false
    #       }
    #     status_code: [
    #                   200,  # Created Certificate
    #                   201,  # Created
    #                   405,  # Invalid input
    #                   409,  # Certificate already exists
    #                   500,  # Internal server error
    #                   ]
    #     body_format: json
    #     validate_certs: "{{ ise_verify }}"
    #     return_content: true
    #     timeout: 600 # in seconds (10 minutes)
    #   register: response
    #   failed_when: (response.status != 200) and (response.status != 500)
    #   ignore_errors: true

    - name: Import Lets Encrypt Root Trusted certificate on {{ inventory_hostname }} via API
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://ise-ppan-test.isedtea.net/api/v1/certs/trusted-certificate/import
        method: POST
        url_username: iseadmin
        url_password: ISEisC00L
        force_basic_auth: yes
        body: |
          { 
            "allowBasicConstraintCAFalse": true,
            "allowMultipleCNCert": false,
            "allowOutOfDateCert": true,
            "allowSHA1Certificates": true,
            "data": "{{lencr_cert_raw.stdout}}",
            "description": "Lets Encrypt Root Certificate",
            "name": "Lets Encrypt Root Certificate",
            "trustForCertificateBasedAdminAuth": false,
            "trustForCiscoServicesAuth": true,
            "trustForClientAuth": false,
            "trustForIseAuth": false,
            "validateCertificateExtensions": false
          }
        status_code: [
                      200,  # Created Certificate
                      201,  # Created
                      405,  # Invalid input
                      409,  # Certificate already exists
                      500,  # Internal server error
                      ]
        body_format: json
        validate_certs: "{{ ise_verify }}"
        return_content: true
        timeout: 600 # in seconds (10 minutes)
      register: response
      failed_when: (response.status != 200) and (response.status != 500)
      ignore_errors: true